added fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -82,7 +82,6 @@ jobs:
           python model/train_model.py
 
       - name: Get Latest Model from S3
-        if: needs.detect-changes.outputs.train == 'true'
         run: |
           BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
           PREFIX=models/
@@ -97,10 +96,20 @@ jobs:
             echo "ERROR: No .tar.gz model file found in S3."
             exit 1
           fi
+          # Extract version from filename
+          filename=$(basename "$latest_model")
+          # e.g., from "xgboost_model_20250630_123045.tar.gz" extract "20250630_123045"
+          version_suffix=$(echo "$filename" | grep -oP '\d{8}_\d{6}')
 
+          if [ -z "$version_suffix" ]; then
+            echo "ERROR: Could not extract version suffix from model filename: $filename"
+            exit 1
+          fi
+
+          # Export to GitHub environment
           echo "TF_VAR_model_data_url=s3://$BUCKET_NAME/$latest_model" >> $GITHUB_ENV
-          echo "TF_VAR_model_version_suffix=${GITHUB_RUN_ID}" >> $GITHUB_ENV
-          echo "endpoint_name=xgboostmodel-endpoint-${GITHUB_RUN_ID}" >> $GITHUB_ENV
+          echo "TF_VAR_model_version_suffix=${version_suffix}" >> $GITHUB_ENV
+          echo "endpoint_name=xgboostmodel-endpoint-${version_suffix}" >> $GITHUB_ENV
 
       - name: Deploy Terraform
         working-directory: ${{ env.TF_DIR }}
